/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AjustesUsuarioController;
import java.awt.Image;
import java.awt.Toolkit;
import model.Usuario;

/**
 *
 * @author DCM
 */
public class AjustesUsuarioWindow extends javax.swing.JFrame {

    /**
     * Creates new form AjustesUsuarioWindow
     */
    public AjustesUsuarioWindow(Usuario user) {
        initComponents();
        setResizable(false);
        setTitle("Menu Ajustes de Usuario");
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        
        AjustesUsuarioController ctr = new AjustesUsuarioController(this, user);
        jButton_Editar.addActionListener(ctr);
        jButton_Borrar.addActionListener(ctr);
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Username = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        jTextField_Contraseña = new javax.swing.JTextField();
        jLabel_NombreCompleto = new javax.swing.JLabel();
        jTextField_NombreCompleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_Editar = new javax.swing.JButton();
        jButton_Borrar = new javax.swing.JButton();
        jLabel_Estatus = new javax.swing.JLabel();
        jComboBox_Estatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Username.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel_Username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Username.setText("Nombre de Usuario");
        jPanel1.add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jTextField_Username.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, -1));

        jLabel_Contraseña.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Contraseña");
        jPanel1.add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        jTextField_Contraseña.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, 20));

        jLabel_NombreCompleto.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel_NombreCompleto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreCompleto.setText("Nombre Completo");
        jPanel1.add(jLabel_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jTextField_NombreCompleto.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_NombreCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajustes Perfil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jButton_Editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Editar.setText("EDITAR");
        jButton_Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 180, -1));

        jButton_Borrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Borrar.setText("BORRAR");
        jButton_Borrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 180, -1));

        jLabel_Estatus.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel_Estatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Estatus.setText("Estatus");
        jPanel1.add(jLabel_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jComboBox_Estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(jComboBox_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Borrar;
    public javax.swing.JButton jButton_Editar;
    public javax.swing.JComboBox<String> jComboBox_Estatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_Estatus;
    private javax.swing.JLabel jLabel_NombreCompleto;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField_Contraseña;
    public javax.swing.JTextField jTextField_NombreCompleto;
    public javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
