/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author jorge
 */
public class FilmDetailsWindow extends javax.swing.JPanel {

    /**
     * Creates new form FilmDetailsWindow
     */
    public FilmDetailsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_tituloDB = new javax.swing.JLabel();
        jLabel_sinopsis = new javax.swing.JLabel();
        jLabel_sinopsisDB = new javax.swing.JLabel();
        jLabel_duracion = new javax.swing.JLabel();
        jLabel_duracionBD = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jLabel_generoBD = new javax.swing.JLabel();
        jLabel_fechaEstreno = new javax.swing.JLabel();
        jLabel_fechaEstrenoBD = new javax.swing.JLabel();
        jLabel_presupuesto = new javax.swing.JLabel();
        jLabel_presupuestoBD = new javax.swing.JLabel();
        jLabel_ganancias = new javax.swing.JLabel();
        jLabel_gananciasBD = new javax.swing.JLabel();
        jLabel_director = new javax.swing.JLabel();
        jLabel_directorBD = new javax.swing.JLabel();
        jLabel_estudio = new javax.swing.JLabel();
        jLabel_estudioB = new javax.swing.JLabel();
        jLabel_actores = new javax.swing.JLabel();
        jLabel_actoresBD = new javax.swing.JLabel();

        jLabel_titulo.setText("Título: ");

        jLabel_sinopsis.setText("Sinopsis:");

        jLabel_duracion.setText("Duración: ");

        jLabel_genero.setText("Género: ");

        jLabel_fechaEstreno.setText("Fecha de estreno: ");

        jLabel_presupuesto.setText("Presupuesto: ");

        jLabel_ganancias.setText("Ganancias");

        jLabel_director.setText("Director: ");

        jLabel_estudio.setText("Estudio: ");

        jLabel_actores.setText("Actores: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ganancias)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_gananciasBD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_presupuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_presupuestoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_fechaEstreno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_fechaEstrenoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_genero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_generoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_estudio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_estudioB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_director)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_directorBD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_titulo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_tituloDB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_duracion)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_duracionBD, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_sinopsis)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_sinopsisDB, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_actoresBD, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_actores))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_titulo)
                                    .addComponent(jLabel_tituloDB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel_actores)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_sinopsis)
                            .addComponent(jLabel_sinopsisDB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_duracion)
                            .addComponent(jLabel_duracionBD)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_actoresBD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_genero)
                    .addComponent(jLabel_generoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fechaEstreno)
                    .addComponent(jLabel_fechaEstrenoBD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_presupuesto)
                    .addComponent(jLabel_presupuestoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ganancias)
                    .addComponent(jLabel_gananciasBD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_director)
                    .addComponent(jLabel_directorBD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_estudio)
                    .addComponent(jLabel_estudioB))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String[] args){
        new FilmDetailsWindow().setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_actores;
    private javax.swing.JLabel jLabel_actoresBD;
    private javax.swing.JLabel jLabel_director;
    private javax.swing.JLabel jLabel_directorBD;
    private javax.swing.JLabel jLabel_duracion;
    private javax.swing.JLabel jLabel_duracionBD;
    private javax.swing.JLabel jLabel_estudio;
    private javax.swing.JLabel jLabel_estudioB;
    private javax.swing.JLabel jLabel_fechaEstreno;
    private javax.swing.JLabel jLabel_fechaEstrenoBD;
    private javax.swing.JLabel jLabel_ganancias;
    private javax.swing.JLabel jLabel_gananciasBD;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_generoBD;
    private javax.swing.JLabel jLabel_presupuesto;
    private javax.swing.JLabel jLabel_presupuestoBD;
    private javax.swing.JLabel jLabel_sinopsis;
    private javax.swing.JLabel jLabel_sinopsisDB;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_tituloDB;
    // End of variables declaration//GEN-END:variables
}
