/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RegisterController;
import java.awt.*;

/**
 *
 * @author DCM
 */
public class RegisterWindow extends javax.swing.JFrame {
    
    public RegisterWindow() {
        initComponents();
        setResizable(false);
        setTitle("Registro de un nuevo usuario");
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        
        RegisterController ctr = new RegisterController(this);
        jButton_Atras.addActionListener(ctr);
        jButton_Registrarme.addActionListener(ctr);
        jComboBox_Rol.addActionListener(ctr);
    }

    @Override
    public final Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }
    
    public boolean camposCompletos(){
        return !jPasswordField_Contraseña.getPassword().toString().equals("") && 
                !jTextField_Username.getText().trim().equals("") &&
               !jTextField_NombreCompleto.getText().trim().equals(""); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jLabel_Username2 = new javax.swing.JLabel();
        jTextField_NombreCompleto = new javax.swing.JTextField();
        jLabel_Rol = new javax.swing.JLabel();
        jComboBox_Rol = new javax.swing.JComboBox<>();
        jLabel_ContraseñaRol = new javax.swing.JLabel();
        jPasswordField_ContraseñaRol = new javax.swing.JPasswordField();
        jButton_Registrarme = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("REGISTRO");
        jPanel1.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 58));

        jLabel_Username.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_Username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Username.setText("Nombre de Usuario");
        jPanel1.add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jTextField_Username.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, -1));

        jLabel_Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Contraseña");
        jPanel1.add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jPasswordField_Contraseña.setBackground(new java.awt.Color(204, 153, 255));
        jPasswordField_Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jPasswordField_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, -1));

        jLabel_Username2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_Username2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Username2.setText("Nombre Completo");
        jPanel1.add(jLabel_Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jTextField_NombreCompleto.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_NombreCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        jLabel_Rol.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_Rol.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rol.setText("Rol");
        jPanel1.add(jLabel_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jComboBox_Rol.setBackground(new java.awt.Color(204, 153, 255));
        jComboBox_Rol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Critico (Especial)", "Administrador (Especial)" }));
        jComboBox_Rol.setBorder(null);
        jComboBox_Rol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jComboBox_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 180, -1));

        jLabel_ContraseñaRol.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_ContraseñaRol.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ContraseñaRol.setText("Contraseña Rol Especial");
        jLabel_ContraseñaRol.setEnabled(false);
        jPanel1.add(jLabel_ContraseñaRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jPasswordField_ContraseñaRol.setBackground(new java.awt.Color(204, 153, 255));
        jPasswordField_ContraseñaRol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField_ContraseñaRol.setEnabled(false);
        jPanel1.add(jPasswordField_ContraseñaRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, -1));

        jButton_Registrarme.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton_Registrarme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ir_1.png"))); // NOI18N
        jButton_Registrarme.setText("Registrarme");
        jButton_Registrarme.setBorderPainted(false);
        jButton_Registrarme.setContentAreaFilled(false);
        jPanel1.add(jButton_Registrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 180, 70));

        jButton_Atras.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton_Atras.setText("Atrás");
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 470, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Negro_Trans_2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 410, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
        dispose();
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_jButton_AtrasActionPerformed

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Atras;
    public javax.swing.JButton jButton_Registrarme;
    public javax.swing.JComboBox<String> jComboBox_Rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Contraseña;
    public javax.swing.JLabel jLabel_ContraseñaRol;
    private javax.swing.JLabel jLabel_Rol;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_Username2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jPasswordField_Contraseña;
    public javax.swing.JPasswordField jPasswordField_ContraseñaRol;
    public javax.swing.JTextField jTextField_NombreCompleto;
    public javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
