/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import java.awt.Image;
import java.awt.Toolkit;
import model.Usuario;
import view.BusquedaWindow;
import view.menu.FilmMenuWindow;
import view.menu.SerieMenuWindow;

/**
 *
 * @author DCM
 */
public class UserWindow extends javax.swing.JFrame {
    Usuario user;
    /**
     * Creates new form UserWindow
     */
    public UserWindow(Usuario user) {
        initComponents();
        setResizable(false);
        setTitle("Menu Principal Usuario");
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        
        this.user = user;
        UserController ctr = new UserController(this, user);
        jButton_Peliculas.addActionListener(ctr);
        jButton_Shows.addActionListener(ctr);
        jButton_Ajustes.addActionListener(ctr);
        jButton_Busqueda.addActionListener(ctr);
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_Busqueda = new javax.swing.JButton();
        jButton_Ajustes = new javax.swing.JButton();
        jButton_Peliculas = new javax.swing.JButton();
        jButton_Shows = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(875, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana Pro Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SERIES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 260, 50));

        jLabel4.setFont(new java.awt.Font("Verdana Pro Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PELICULAS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 260, 50));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Principal de Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Negro_Trans_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 490, 50));

        jButton_Busqueda.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton_Busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa (1).png"))); // NOI18N
        jButton_Busqueda.setText("Busqueda Avanzada");
        jButton_Busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 320, 30));

        jButton_Ajustes.setForeground(new java.awt.Color(51, 102, 255));
        jButton_Ajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GestionUsuarios (1).png"))); // NOI18N
        jButton_Ajustes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Ajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_Ajustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 70, 40));

        jButton_Peliculas.setForeground(new java.awt.Color(0, 102, 255));
        jButton_Peliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/claqueta.png"))); // NOI18N
        jButton_Peliculas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Peliculas.setBorderPainted(false);
        jButton_Peliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_Peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 440));

        jButton_Shows.setForeground(new java.awt.Color(0, 102, 255));
        jButton_Shows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tele.png"))); // NOI18N
        jButton_Shows.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Shows.setBorderPainted(false);
        jButton_Shows.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_Shows, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo-1557683311-eac922347aa1.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(875, 440));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -7, 850, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Ajustes;
    public javax.swing.JButton jButton_Busqueda;
    public javax.swing.JButton jButton_Peliculas;
    public javax.swing.JButton jButton_Shows;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
