/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.anadir;

import controller.anadir.AnadirDirectorController;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author DCM
 */
public class AnadirDirectorWindow extends javax.swing.JFrame {

    /**
     * Creates new form AñadirDirectorWindow
     */
    public AnadirDirectorWindow() {
        initComponents();
        setResizable(false);
        setTitle("Añadir Director");
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        
        AnadirDirectorController ctr = new AnadirDirectorController(this);
        jButton_AñadirDirector.addActionListener(ctr);
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }

        public boolean camposCompletos(){
        return !"".equals(jTextField_Nombre.getText().trim()) &&
               !"".equals(jTextField_LugarNacimiento.getText().trim()) &&
               !"".equals(jTextField_Nacionalidad.getText().trim()) &&
               jDateChooser_FechaNacimiento.getDate() != null &&
               (jRadioButton_Femenino.isSelected() || jRadioButton_Masculino.isSelected());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField_LugarNacimiento = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jTextField_Nacionalidad = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_Nominaciones = new javax.swing.JTextArea();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea_Premios = new javax.swing.JTextArea();
        jDateChooser_FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jRadioButton_Masculino = new javax.swing.JRadioButton();
        jRadioButton_Femenino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_AñadirDirector = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_Nombre.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        jLabel62.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Nombre");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel63.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Sexo");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel64.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel65.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Lugar de Nacimiento");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jTextField_LugarNacimiento.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_LugarNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_LugarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 200, -1));

        jLabel66.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Nacionalidad");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jTextField_Nacionalidad.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nacionalidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 200, -1));

        jLabel67.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Nominaciones");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jTextArea_Nominaciones.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea_Nominaciones.setColumns(20);
        jTextArea_Nominaciones.setRows(5);
        jTextArea_Nominaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane7.setViewportView(jTextArea_Nominaciones);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel68.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Premios");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jTextArea_Premios.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea_Premios.setColumns(20);
        jTextArea_Premios.setRows(5);
        jTextArea_Premios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane8.setViewportView(jTextArea_Premios);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        jDateChooser_FechaNacimiento.setBackground(new java.awt.Color(204, 255, 255));
        jDateChooser_FechaNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jDateChooser_FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 200, -1));

        jRadioButton_Masculino.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jRadioButton_Masculino.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Masculino.setText("Masculino");
        jPanel1.add(jRadioButton_Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jRadioButton_Femenino.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jRadioButton_Femenino.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Femenino.setText("Femenino");
        jPanel1.add(jRadioButton_Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Añadir Director");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, 60));

        jButton_AñadirDirector.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_AñadirDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ir_1.png"))); // NOI18N
        jButton_AñadirDirector.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_AñadirDirector.setBorderPainted(false);
        jButton_AñadirDirector.setContentAreaFilled(false);
        jPanel1.add(jButton_AñadirDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Negro_Trans_2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 320, 680));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 400, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirDirectorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton_AñadirDirector;
    public com.toedter.calendar.JDateChooser jDateChooser_FechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton_Femenino;
    public javax.swing.JRadioButton jRadioButton_Masculino;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTextArea jTextArea_Nominaciones;
    public javax.swing.JTextArea jTextArea_Premios;
    public javax.swing.JTextField jTextField_LugarNacimiento;
    public javax.swing.JTextField jTextField_Nacionalidad;
    public javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
