/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.editar;

import controller.editar.EditarPeliculaController;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author DCM
 */
public class EditarPeliculaWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditarPeliculaWindow
     */
    public EditarPeliculaWindow() {
        initComponents();
        setResizable(false);
        setTitle("Editar Pelicula.");
        setLocationRelativeTo(null); 
        setIconImage(getIconImage());
        
        EditarPeliculaController ctrl = new EditarPeliculaController(this);
        jButton_Buscar.addActionListener(ctrl);
        jButton_Editar.addActionListener(ctrl);
    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField_Titulo = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_Sinopsis = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jTextField_Genero = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField_Presupuesto = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField_Ganancias = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField_Imagen = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField_DirectorID = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField_EstudioID = new javax.swing.JTextField();
        jDateChooser_FechaEstreno = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton_Buscar = new javax.swing.JButton();
        jTextField_BuscarID = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jButton_Editar = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jTextField_Duracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Titulo");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jTextField_Titulo.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 180, -1));

        jLabel37.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Sinopsis");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jTextArea_Sinopsis.setBackground(new java.awt.Color(204, 153, 255));
        jTextArea_Sinopsis.setColumns(20);
        jTextArea_Sinopsis.setRows(5);
        jTextArea_Sinopsis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane5.setViewportView(jTextArea_Sinopsis);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel38.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Genero");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jTextField_Genero.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Genero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, -1));

        jLabel39.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Fecha Estreno");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel40.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Presupuesto");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jTextField_Presupuesto.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Presupuesto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 180, -1));

        jLabel41.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Ganancias");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        jTextField_Ganancias.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Ganancias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 180, -1));

        jLabel42.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Imagen");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jTextField_Imagen.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 180, -1));

        jLabel43.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Director ID");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        jTextField_DirectorID.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_DirectorID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_DirectorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 180, -1));

        jLabel44.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Estudio ID");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jTextField_EstudioID.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_EstudioID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_EstudioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 180, -1));

        jDateChooser_FechaEstreno.setBackground(new java.awt.Color(204, 153, 255));
        jDateChooser_FechaEstreno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jDateChooser_FechaEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 180, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Pelicula");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jButton_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ir_1.png"))); // NOI18N
        jButton_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Buscar.setBorderPainted(false);
        jButton_Buscar.setContentAreaFilled(false);
        jPanel1.add(jButton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 180, 70));

        jTextField_BuscarID.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_BuscarID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_BuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 180, -1));

        jLabel45.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Pelicula_ID");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jButton_Editar.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Editar.setText("EDITAR");
        jButton_Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 180, -1));

        jLabel46.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Duracion");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jTextField_Duracion.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Duracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 180, -1));

        jLabel3.setBackground(new java.awt.Color(204, 153, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Negro_Trans_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 530, 650));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 600, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPeliculaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPeliculaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPeliculaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPeliculaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPeliculaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Buscar;
    public javax.swing.JButton jButton_Editar;
    public com.toedter.calendar.JDateChooser jDateChooser_FechaEstreno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTextArea jTextArea_Sinopsis;
    public javax.swing.JTextField jTextField_BuscarID;
    public javax.swing.JTextField jTextField_DirectorID;
    public javax.swing.JTextField jTextField_Duracion;
    public javax.swing.JTextField jTextField_EstudioID;
    public javax.swing.JTextField jTextField_Ganancias;
    public javax.swing.JTextField jTextField_Genero;
    public javax.swing.JTextField jTextField_Imagen;
    public javax.swing.JTextField jTextField_Presupuesto;
    public javax.swing.JTextField jTextField_Titulo;
    // End of variables declaration//GEN-END:variables
}
