/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.editar;

import controller.editar.EditarDirectorController;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author DCM
 */
public class EditarDirectorWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditarDirectorWindow
     */
    public EditarDirectorWindow() {
        initComponents();
        setResizable(false);
        setTitle("Editar Director.");
        setLocationRelativeTo(null); 
        setIconImage(getIconImage());
        
        EditarDirectorController ctrl = new EditarDirectorController(this);
        jButton_Buscar.addActionListener(ctrl);
        jButton_Editar.addActionListener(ctrl);
    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField_LugarNacimiento = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jTextField_Nacionalidad = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_Nominaciones = new javax.swing.JTextArea();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea_Premios = new javax.swing.JTextArea();
        jDateChooser_FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jRadioButton_Masculino = new javax.swing.JRadioButton();
        jRadioButton_Femenino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Buscar = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        jTextField_BuscarID = new javax.swing.JTextField();
        jButton_Editar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_Nombre.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 180, -1));

        jLabel62.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Nombre");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel63.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Sexo");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel64.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel65.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Lugar de Nacimiento");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jTextField_LugarNacimiento.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_LugarNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_LugarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, -1));

        jLabel66.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Nacionalidad");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jTextField_Nacionalidad.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_Nacionalidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 180, -1));

        jLabel67.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Nominaciones");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jTextArea_Nominaciones.setBackground(new java.awt.Color(204, 153, 255));
        jTextArea_Nominaciones.setColumns(20);
        jTextArea_Nominaciones.setRows(5);
        jTextArea_Nominaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane7.setViewportView(jTextArea_Nominaciones);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 410, 170, -1));

        jLabel68.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Premios");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        jTextArea_Premios.setBackground(new java.awt.Color(204, 153, 255));
        jTextArea_Premios.setColumns(20);
        jTextArea_Premios.setRows(5);
        jTextArea_Premios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane8.setViewportView(jTextArea_Premios);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 530, 170, -1));

        jDateChooser_FechaNacimiento.setBackground(new java.awt.Color(204, 153, 255));
        jDateChooser_FechaNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jDateChooser_FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 180, -1));

        jRadioButton_Masculino.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jRadioButton_Masculino.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Masculino.setText("Masculino");
        jPanel1.add(jRadioButton_Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jRadioButton_Femenino.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jRadioButton_Femenino.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Femenino.setText("Femenino");
        jPanel1.add(jRadioButton_Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Director");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 280, 60));

        jButton_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ir_1.png"))); // NOI18N
        jButton_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Buscar.setBorderPainted(false);
        jButton_Buscar.setContentAreaFilled(false);
        jPanel1.add(jButton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 70));

        jLabel69.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Director_ID");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField_BuscarID.setBackground(new java.awt.Color(204, 153, 255));
        jTextField_BuscarID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_BuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, -1));

        jButton_Editar.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Editar.setText("EDITAR");
        jButton_Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Negro_Trans_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 510, 650));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDirectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDirectorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Buscar;
    public javax.swing.JButton jButton_Editar;
    public com.toedter.calendar.JDateChooser jDateChooser_FechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton_Femenino;
    public javax.swing.JRadioButton jRadioButton_Masculino;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTextArea jTextArea_Nominaciones;
    public javax.swing.JTextArea jTextArea_Premios;
    public javax.swing.JTextField jTextField_BuscarID;
    public javax.swing.JTextField jTextField_LugarNacimiento;
    public javax.swing.JTextField jTextField_Nacionalidad;
    public javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
